### ISSUE TITLE
Geolocation needs testing before on several devices

### ISSUE THREAD

**Issue by ff6347** [technologiestiftung/giessdenkiez-de#117]
Before we can add Geolocation to the project we really need to test this on several devices.

Seems to work on

- [x] FFfox (latest)
- [x] Chrome (latest)
- [ ] Safari (latest)
- [ ] iOS
- [ ] Android

Local testing with Browserstack created problems due to lack of https in Safari

**Comment by bnjmnsbl** [comment]
Doesn't work on Safari (iPhone) either...
