### ISSUE TITLE
Option to use 2D map

### ISSUE THREAD

**Issue by komape** [technologiestiftung/giessdenkiez-de#144]
Currently it is only possible to use a 3D map (at least it looks like I'm not looking from above, more like from the side). This can cause problems on telephones and low equipped computers because form the moment the user drags the map it takes some time until the new view is rendered. It can make the site actually not useable.

A 2D map takes less rendering time than a 3D map. That is why I think you should at least give the option to use 2D instead of 3D.

**Comment by fabianmoronzirfas** [comment]
Hi @komape thanks for the issue. We are still evaluating solutions to reduce the load for mobile devices. We will take your idea into consideration.
