### ISSUE TITLE
visualised water-level (rain + user)?

### ISSUE THREAD

**Issue by sebastian-meier** [technologiestiftung/giessdenkiez-de#152]
Discussion: Currently the points visualise the rainfall, this is also clearly stated in the legend. Question, should we combine rain + water from citizens? 

The idea arouse from a discussion with users. When you look into the map and want to know which tree to water, it would be nice, if you could immediately see, which has already been watered.

The same goes for the linechart and liter values on the details page. We could transform the linechart to a stacked-linechart and show the combined liters and in brackets the liters form rain and citizens separated.

We already acquire a list of trees, that have been watered by users, adding the liters would not be too hard and data size is acceptable, same goes for the line-chart.

**Comment by julizet** [comment]
improve visualization of water amount each tree has received by using:
- stacked area chart / stacked bar chart / staked line chart
- add tooltip on hover

**Comment by julizet** [comment]
will add y-axis labeling & transition of bar charts end of this week/beginning of next week

**Comment by dnsos** [comment]
@julizet, can this be closed since PR #250 is already merged?

**Comment by vogelino** [comment]
> @julizet, can this be closed since PR #250 is already merged?

Yes!
