### ISSUE TITLE
add filter / option to show most endangered trees

### ISSUE THREAD

**Issue by julizet** [technologiestiftung/giessdenkiez-de#158]
for most of the users the green dots are misleading --> feels like all the trees have enough water
a filter might help to just filter for the most endangered trees. Filter could aggregate: young trees, trees which are watered the least, trees with no abonemments etc.

**Comment by yannickoo** [comment]
Hey @julizet 👋 I just wanted to let you know there is #205 which will allow you to filter by water need. A new filter for showing non-adopted trees sounds nice!

**Comment by vogelino** [comment]
Now that @yannickoo PR #358 is merged, the question would be whether we want to indicate other parameters that help determine how endangered is a tree (sicknesses, type, soil, etc...)? Otherwise, I would consider this done and close this issue.
