### ISSUE TITLE
Use own email provider

### ISSUE THREAD

**Issue by ff6347** [technologiestiftung/giessdenkiez-de#161]
We have around 5% unverified users emails. We could imporve there by

- [ ] allowing to resend the mail
- [ ] make a note where this mail will come from
- [ ] tweak Auth0 mail settings

**Comment by donni106** [comment]
Is a German verification mail possible with Auth0? This could also help some people.

**Comment by fabianmoronzirfas** [comment]
@donni106 Yes it is possible. See https://dev.auth0.com/docs/email/providers I'll add this to the backlog
