### ISSUE TITLE
spellcheck text

### ISSUE THREAD

**Issue by fabianmoronzirfas** [technologiestiftung/giessdenkiez-de#166]
…

**Comment by julizet** [comment]
wasn`t this done by you the last days?
If not, I could perform another spellcheck

**Comment by fabianmoronzirfas** [comment]
No. I don't do spellchecks. There are always typos that slip by. Problem is that we have quite some Text directly in the source. This should also not be like this. Could you take a look into spellchecking at least content.jsx?

**Comment by julizet** [comment]
Sure, I`ll have a look into the spellcheks tomorrow on my trip home
