### ISSUE TITLE
Improve on site information about the data sources

### ISSUE THREAD

**Issue by ff6347** [technologiestiftung/giessdenkiez-de#168]
This can be done by just adding 1 or two paragraphs what kind of data is behind that links. Also a link to the article from @AlexandraKapp https://lab.technologiestiftung-berlin.de/projects/fisbroker-to-qgis/de/ would be good.

**Comment by julizet** [comment]
not sure whether there was already some improvement done.

This is the current status
<img width="366" alt="Bildschirmfoto 2021-02-23 um 12 24 01" src="https://user-images.githubusercontent.com/52455010/108837082-0442ca00-75d2-11eb-859b-a1bdce614270.png">

I suggest to add even one or two more sentences to explain what the FIS-Broker and the Baumkataster.

I'd also like to remove this paragraph "Aus verschiedenen Gründen sind leider noch nicht alle Berliner Stadtbäume aufgeführt. Wir arbeiten aber daran, die Datenlage zu verbessern und eine möglichst vollständige Darstellung des Berliner Baumbestandes zu erreichen. Die aktuellen Datenquellen sind:" cuz @Lisa-Stubert  already fixed this issue

What do you think @ff6347 ?

**Comment by ff6347** [comment]
Not sure. Do we have all the trees? Maybe @Lisa-Stubert can tell us more
