### ISSUE TITLE
rename repo to giessdenkiez

### ISSUE THREAD

**Issue by fabianmoronzirfas** [technologiestiftung/giessdenkiez-de#177]
IMO It would be better in terms discoverability. Also we don't need the tsb prefix in the name. We are the TSB.

**Comment by fabianmoronzirfas** [comment]
@bnjmnsbl @sebastian-meier @julizet are you fine with this? GitHub normally takes care of the redirect and we can change this in the source as well

**Comment by bnjmnsbl** [comment]
let's do it

**Comment by fabianmoronzirfas** [comment]
Cool. I will have to make sure that we don't have downtime with Netlify. So I don't do this right away but I put it on my plate

**Comment by fabianmoronzirfas** [comment]
This will take the following steps:

1. stop all builds + disable auto deploys on netlify
2. rename the repo on github
3. relink the repo on netlify (should trigger a build)
4. enable auto deploys on netlify

**Comment by fabianmoronzirfas** [comment]
Repo renaming and redeploy worked.

What did we learn?

- env variables will be gone
- never set NODE_ENV in netlify.toml since the npm ci/i will only install production dependencies 🤦
