### ISSUE TITLE
Create testing/staging DB

### ISSUE THREAD

**Issue by ff6347** [technologiestiftung/giessdenkiez-de#182]
For not fooling around with the original DB we should have a dev version. So we also could link the vercel function during development.

- [ ] Should maybe have reset every week (or day) and sync to the original one.
- [ ] Should be automated using github actions

This might help https://gist.github.com/fabianmoronzirfas/b331f2869c799d6f41e5bd72ef668a6e

**Comment by julizet** [comment]
test DB is already running --> can this issue be closed @ff6347 ?

**Comment by ff6347** [comment]
yes. We still don't have a proper way to provision a new DB but this is another thing.
