### ISSUE TITLE
Show "caretaker label" as circle to each tree node (on map)

### ISSUE THREAD

**Issue by julizet** [technologiestiftung/giessdenkiez-de#184]
## Background: Why this issue? 

- second step of [Issue #183](https://github.com/technologiestiftung/tsb-trees-frontend/issues/183)

## Deliverables: How to fix the issue?

- add another circle (green outline?) to tree nodes which are nurtured by Berlin authorities to the frontend
- to avoid performance issues: show caretaker circle not before a specific zoom level
- add the "caretaker labeled" trees to the filter of adopted trees OR create a very own filter for "caretaker labeled trees"

## Output: Gain of fixing the issue?

- if authorities are taking care or not should be visible on map (without clicking at a specific tree)

## Issue creation checklist
- [x] I have attached one of the priority labels `HIGH`, `MIDDLE`, `LOW`
- [x] I have attached other labels with regard to the issues purpose (i.e.`enhancement`, `bug`, `community feedback`)

**Comment by raphael-arce** [comment]
Closing as no longer relevant
