### ISSUE TITLE
Demo version for CityLAB exhibition

### ISSUE THREAD

**Issue by ff6347** [technologiestiftung/giessdenkiez-de#192]
Should

- [x] Mock auth0
- [x] mock the post api calls 
- [x] Allow to see the ui elements for logged in users
- [x] run it on a subdomain https://demo.giessdenkiez.de
- [ ] remove ui Elements 
- [x] have ssl cert for it

**Comment by fabianmoronzirfas** [comment]
Some problems I have here are:

- Why do some request get past the MSW module feels random
- Seems like it works better with open developer console
