### ISSUE TITLE
Search filter BUG

### ISSUE THREAD

**Issue by julizet** [technologiestiftung/giessdenkiez-de#195]
## Background: Why this issue? 

- watered trees don`t show up when filter "in den letzten 30 Tagen gegossen"

## Deliverables: How to fix the issue?

- fix filter bug
- add all the missing trees (manually?)

## Output: Gain of fixing the issue?

- working filter
(otherwise app doesn`t make that much sense for coordinating watering actions)

watered tree....
![Bildschirmfoto 2020-07-20 um 13 22 03](https://user-images.githubusercontent.com/52455010/87936943-0f5dd680-ca94-11ea-8765-3d92564264d1.png)

...doesn`t show up
![Bildschirmfoto 2020-07-20 um 13 22 15](https://user-images.githubusercontent.com/52455010/87936947-0ff66d00-ca94-11ea-8d69-2288aa547729.png)

## Issue creation checklist
- [x] I have attached one of the priority labels `HIGH`, `MIDDLE`, `LOW`
- [x] I have attached other labels with regard to the issues purpose (i.e.`enhancement`, `bug`, `community feedback`)

**Comment by fabianmoronzirfas** [comment]
@julizet can your review if the PR #197 https://deploy-preview-197--internetoftrees.netlify.app/ fixes this issue?

**Comment by julizet** [comment]
I tested several trees (some adopted, some not // some watered, some not) and the filter works perfectly for me
