### ISSUE TITLE
Feature Request: Filter by trees with high water demand

### ISSUE THREAD

**Issue by ff6347** [technologiestiftung/giessdenkiez-de#205]

**Comment by yannickoo** [comment]
@ff6347 I have created a PR for the initial implementation of this filter: https://github.com/technologiestiftung/giessdenkiez-de/pull/358

**Comment by vogelino** [comment]
@yannickoo Did add a great PR with a new water need filter which I just merged. I'm now closing this issuer. Thank to @yannickoo again!
