### ISSUE TITLE
Alternative widget for tree age selection 

### ISSUE THREAD

**Issue by joergreichert** [technologiestiftung/giessdenkiez-de#216]
## Background: Why this issue? 

Currently it is hard to select the age range with the slider when this age range is low resp. narrow, e.g. 0 to 5. because the range is 0 to 320 and you have to be very subtle to hit those numbers.

## Deliverables: How to fix the issue?

Use two number spinner boxes (with some logic, so that the first one cannot have a higher number than the second one).
Even some presets could be helpful, so can quickly select the ranges 0 to 3, 3 to 15, older 15 (according to the watering guidelines, but this might be an extra issue tracker item). Those spinner widgets might also be used for filtering by liters of water a tree has received by rain / manual watering (but also out of scope of this issue).

## Output: Gain of fixing the issue?

Easier selection of age ranges (by directly typing the numbers in the text box resp. using the spinner next to it to raise resp. lower then number).

## Issue creation checklist
- [ ] I have attached one of the priority labels `HIGH`, `MIDDLE`, `LOW` --> LOW
- [ ] I have attached other labels with regard to the issues purpose (i.e.`enhancement`, `bug`, `community feedback`) --> ENHANCEMENT

**Comment by HenrietteN** [comment]
Closing this issue as we have updated the feature for selecting the age range: https://www.giessdenkiez.de/map in the filter settings, we also added a bar chart illustration for the age distribution of trees.
