### ISSUE TITLE
Harvester not populating data into db

### ISSUE THREAD

**Issue by syedmbzaidi** [technologiestiftung/giessdenkiez-de#225]
Hi There,
I have been trying to run the harvester.py file but currently, I am facing a Blocker at my end. Harvester is running fine but it is not populating data in the Trees DB hosted at AWS and throwing no error.

.env file is loaded properly. I have logged the parameters of the database. Correct endpoints are being used. It is able to read the data from **radolan_harvester** table. But unable to insert data in subsequent queries. Please tell me if something further needs to be done to get the data populated into DB.

**Comment by ff6347** [comment]
@sebastian-meier can you say something what the harvester needs to run properly.

**Comment by sebastian-meier** [comment]
1. of all, there needs to be rain. Otherwise there will be not data inserted.
2. the table radolan_geometry, needs to hold a point raster of the target area, which is of equivalent grid structure as the DWD RADOLAN data. Because the weather data will be attached to those centroids.

**Comment by syedmbzaidi** [comment]
@sebastian-meier Thanks for the reply.
I have data for rain as well in the dataset I am downloading. The code is running without any error. In the logs, I can see the insertion commands being run. But when I go to the database, there is no data inserted into the tables. 
my radolan_geometry and radolan_datais are empty.  

![image](https://user-images.githubusercontent.com/73298336/100587435-d7438b80-32f0-11eb-9072-e24ade48df5f.png)


I have deployed the backend using Terraform (DB creation, ECS, S3 creation)
Do I need to do anything further for the insertion of the data?

**Comment by syedmbzaidi** [comment]
Can It be because of the following error? 

![image](https://user-images.githubusercontent.com/73298336/100605290-01547800-3308-11eb-9a68-df3f510163a9.png)

fiona.ogrext:Failed to auto identify EPSG: 7

**Comment by ff6347** [comment]
@syedmbzaidi Was this issue resolved?
