### ISSUE TITLE
Find yourself by location (mobile)

### ISSUE THREAD

**Issue by ff6347** [technologiestiftung/giessdenkiez-de#228]

**Comment by julizet** [comment]
suggestion: usage of the mapbox `geolocateControl()` 

I once used it for my ttn-tracker (which is obviusly not receiving any attention anymore).
However, geo-locating still works fine. This is the code snippet Is used:

```javascript
  // +++ function to user location on the map (blue dot) +++
  // +++  important: only works within save environment (https or localhost) +++
  const geoLocate = new mapboxgl.GeolocateControl({
    positionOptions: {
      enableHighAccuracy: true,
    },
    trackUserLocation: true,
    showUserLocation: true,
  });
  map.addControl(geoLocate);
```

**Comment by ff6347** [comment]
We had some issues on mobile with it. That’s why we decided against it before the release. Let’s review that again next week

**Comment by ff6347** [comment]
#117 #133
