### ISSUE TITLE
How much water does the tree need per week/month/day

### ISSUE THREAD

**Issue by ff6347** [technologiestiftung/giessdenkiez-de#230]

**Comment by julizet** [comment]
suggestion: add small info (box, icon, etc.) with static water amounts to the sidebar of each tree.

More sophisticated approach would be to calculate the water amount for each tree by some of the following data:
- tress species
- trees age
- trees location (and the corresponding soil type)
- other data like sunshine hours, temperature, cloud coverage satellite data

**Comment by vogelino** [comment]
Related: https://github.com/technologiestiftung/giessdenkiez-de/discussions/234

**Comment by raphael-arce** [comment]
Closing as no longer relevant
