### ISSUE TITLE
Add more information to Pumpen tooltips

### ISSUE THREAD

**Issue by julizet** [technologiestiftung/giessdenkiez-de#239]
- status
- address
- type of pump
- image (we have an image file name for most pumps, but where is the API for this image?)

**Comment by danielsippel** [comment]
All the image filenames mentioned in `public/data/pumps.geojson` refer to Wikimedia Commons.

e.g. `"image": "File:Plumpe 11 Marzahn Schragenfeldstraße-Bäckerpfuhl (8).jpg"`

1) We could show the image in tooltip if image specific license allows it (afaik all licenses on wikimedia commons match for that case, possibly with attribution).

-> Wikimedia Commons API request to retrieve the img url & license details ->
`https://commons.wikimedia.org/w/api.php?action=query&format=json&titles=Image:Plumpe_11_Marzahn_Schragenfeldstra%C3%9Fe-B%C3%A4ckerpfuhl_(8).jpg&prop=imageinfo&iiprop=url|extmetadata`

👍 

2) or probably just set a link to the Wikimedia Commons page

-> Wikimedia Commons page url -> https://commons.wikimedia.org/wiki/File:Plumpe_11_Marzahn_Schragenfeldstra%C3%9Fe-B%C3%A4ckerpfuhl_(8).jpg

**Comment by ff6347** [comment]
Hi @danielsippel I think we already discussed that. Since the trees are in focus of the platform it would be wired to have images of pumps but not of trees. If we enrich the UI with more information about the trees (like images from example tress and leaves) it would be okay to also use the images of the pumps. Since we  don't have these I would vote against using the pump images.

@julizet your the PO. Do we have a jira ticket for that already?

**Comment by julizet** [comment]
As @ff6347 already mentioned, the focus whould be first on the trees and second to the pumps. So far, ticket no. gdk-20 in Jira is dealing with preview images of a tree. However, this is a ticket  is linked to "Feature Wishlist" which means that we're not actively working on this ticket buth rather put it on our wishlist in case we'll have some free time for implementation left. Btw: I really like the approach of [New York City Street Tree Map](https://tree-map.nycgovparks.org/tree-map/tree/3367209) which just shows the image of the leaf rather than the whole tree. This makes it easier to identify the tress species.

I would not implement a preview images for pumps beforehand. First it would be more important to style the extended tooltip (covered by Jira ticket no. gdk-19) to show the attributes which were already fetched by [Lisas commit ](https://github.com/technologiestiftung/giessdenkiez-de/pull/243/commits/c78d9e63fc6549482db109067ab2dd96b831b25e). 

<img width="1321" alt="Bildschirmfoto 2021-04-30 um 10 49 35" src="https://user-images.githubusercontent.com/52455010/116671880-c41d1080-a9a1-11eb-82ce-f4f6ad7e5408.png">

I would like to ask @dnsos to finish the styling for those attributes (without image) first.
