### ISSUE TITLE
Filter "bereits adoptiert" should also show non adopted trees but in another color

### ISSUE THREAD

**Issue by vogelino** [technologiestiftung/giessdenkiez-de#240]
## Background: Why this issue? 
The filter"breits adoptiert" shows the engagement of the community on the platform but it could also help to choose for a tree to adopt that isn't yet adopted. For this purpose, all trees should be displayed and those that are already adopted should be highlighted.

## Deliverables: How to fix the issue?
Show all trees and display them differently than  those adopted (gray?)

## Output: Gain of fixing the issue?
Helps to find a tree to adopt.

## Issue creation checklist
- [ ] I have attached one of the priority labels `HIGH`, `MIDDLE`, `LOW`
- [ ] I have attached other labels with regard to the issues purpose (i.e.`enhancement`, `bug`, `community feedback`)

**Comment by HenrietteN** [comment]
We currently don't have the filter of all the adopted trees any longer, but might implement it again soon. Furthermore, we have generally adapted the color code of the trees, and could therefore add another color for adopted trees and those taken care of by the city authorities.
