### ISSUE TITLE
update node >= v12

### ISSUE THREAD

**Issue by ff6347** [technologiestiftung/giessdenkiez-de#245]
## Background: Why this issue? 

Node v10 will be out of LTS soon https://nodejs.org/en/about/releases/

## Deliverables: How to fix the issue?

Update .nvmrc to contain a new version

## Output: Gain of fixing the issue?

LTS version of Node.js

## Issue creation checklist
- [x] I have attached one of the priority labels `HIGH`, `MIDDLE`, `LOW`
- [x] I have attached other labels with regard to the issues purpose (i.e.`enhancement`, `bug`, `community feedback`)

**Comment by vogelino** [comment]
Closing this as we are currently using node version `14.17.4`
