### ISSUE TITLE
Update Mapbox-gl to v2

### ISSUE THREAD

**Issue by ff6347** [technologiestiftung/giessdenkiez-de#269]
@vogelino Could you take this on? It would be nice to see if this fixes the M1 problem.
We will have to add the preview URL to the Mapbox account.

**Comment by vogelino** [comment]
Will do 👍

**Comment by vogelino** [comment]
@ff6347 Which package exactly should be updated? I see no `mapbox-gl` package. I see:
- `@mapbox/vector-tile`
- `react-map-gl`
Both of which have a version higher than 2
