### ISSUE TITLE
Missing attribution for OpenStreetMap

### ISSUE THREAD

**Issue by joshinils** [technologiestiftung/giessdenkiez-de#330]
## Background: Why this issue? 
While looking at the site, there is no attribution for OpenStreetMap.

## Deliverables: How to fix the issue?
Add something described here: [How to credit OpenStreetMap](https://www.openstreetmap.org/copyright)

## Output: Gain of fixing the issue?
Correct attribution for using OpenStreetMap data.

This is not a bug per se, but needed indeed. I would like for you to please add the required attribution for the map.

**Comment by ff6347** [comment]
@joshinils Thank you for the heads up. Can you take a look at the

**Comment by ff6347** [comment]
> Since our map comes from Mapbox and not directly from OSM and only the pumps data is from OSM. I'm wondering if this is the right location for the attribution.

Hm. Looks like we missed this one https://docs.mapbox.com/help/glossary/attribution/

**Comment by vogelino** [comment]
Fixed with #377. Thanks for reporting! 🙏
