### ISSUE TITLE
HIGH registration not possible

### ISSUE THREAD

**Issue by offtaste** [technologiestiftung/giessdenkiez-de#345]
## Background: Why this issue? 

-I wanted to register to fill in how much water I gave to which trees.
Klicking on the registration button always brings you to the project description on Browser. On mobile device it brings you back to the map. No registration possible.
One time I came through to the registration side (safari), filled out the form and nothing happened when I sent the form.

## Deliverables: How to fix the issue?

-relink the registration or fix the registration itself.

## Output: Gain of fixing the issue?

-registration for new waterers :)

## Issue creation checklist
- [x] I have attached one of the priority labels `HIGH`, `MIDDLE`, `LOW`
- [x] I have attached other labels with regard to the issues purpose (i.e.`enhancement`, `bug`, `community feedback`)

**Comment by vogelino** [comment]
Hi @offtaste ! Thank you for reporting this bug. We are looking into it. Could you please provide us more information about which OS and browser (and version) you are using, so we can try to reproduce the Bug? Cheers ☮️

**Comment by vogelino** [comment]
@offtaste we have fixed some bugs related to authentication and it might have also solved your issues. Please let me know if you keep experiencing issues. I'll close this ticket for now.
