### ISSUE TITLE
Trees not coloured

### ISSUE THREAD

**Issue by panketaucher** [technologiestiftung/giessdenkiez-de#379]
Einige Bäume werden bei Suche & Filter unter Bereits adoptiert und In den letzten 30 Tagen gegossen nicht eingefärbt. Sie färben sich bloß beim Klick auf Niederschläge ein und werden sichtbar.
 
 https://giessdenkiez.de/tree/_2100157419
https://giessdenkiez.de/tree/_2100157b5d

**Comment by ff6347** [comment]
I took a look into the DB. There are no trees with these ids???

**BUT**

In our trees.csv I can find them:

```
curl -s --compressed https://tsb-trees.s3.eu-central-1.amazonaws.com/trees.csv.gz | grep "_2100157419\|_2100157b5d"
```

@Lisa-Stubert Did we regenerate the `trees.csv` when we updated the DB with with new trees?

**Comment by ff6347** [comment]
Sorry. I was wrong. I had old credemtials in my TablePlus. The trees exist in the DB

**Comment by ff6347** [comment]
| id          | artdtsch                        | geom                               |
|-------------|---------------------------------|------------------------------------|
| _2100157419 | Japanische Zierkirsche 'Kanzan' | SRID=4326;POINT(13.38329 52.55875) |
| _2100157b5d | Japanische Zierkirsche 'Kanzan' | SRID=4326;POINT(13.37779 52.55842) |

**Comment by ff6347** [comment]
| time                          | amount | username     | tree_id     |
|-------------------------------|--------|--------------|-------------|
| 2021-07-09 22:32:23.634662+00 | 50     | panketaucher | _2100157b5d |
| 2021-07-09 22:32:35.09937+00  | 50     | panketaucher | _2100157b5d |
| 2021-07-09 22:32:46.35592+00  | 50     | panketaucher | _2100157b5d |
| 2021-08-06 18:48:53.282774+00 | 50     | panketaucher | _2100157b5d |
| 2021-08-06 18:48:55.012333+00 | 50     | panketaucher | _2100157b5d |
| 2021-08-06 18:49:04.576545+00 | 50     | panketaucher | _2100157b5d |

**Comment by ff6347** [comment]
| time                          | id          | artdtsch                        | geom                               | amount | username     |
|-------------------------------|-------------|---------------------------------|------------------------------------|--------|--------------|
| 2021-07-09 22:32:23.634662+00 | _2100157b5d | Japanische Zierkirsche 'Kanzan' | SRID=4326;POINT(13.37779 52.55842) | 50     | panketaucher |
| 2021-07-09 22:32:35.09937+00  | _2100157b5d | Japanische Zierkirsche 'Kanzan' | SRID=4326;POINT(13.37779 52.55842) | 50     | panketaucher |
| 2021-07-09 22:32:46.35592+00  | _2100157b5d | Japanische Zierkirsche 'Kanzan' | SRID=4326;POINT(13.37779 52.55842) | 50     | panketaucher |
| 2021-08-06 18:48:53.282774+00 | _2100157b5d | Japanische Zierkirsche 'Kanzan' | SRID=4326;POINT(13.37779 52.55842) | 50     | panketaucher |
| 2021-08-06 18:48:55.012333+00 | _2100157b5d | Japanische Zierkirsche 'Kanzan' | SRID=4326;POINT(13.37779 52.55842) | 50     | panketaucher |
| 2021-08-06 18:49:04.576545+00 | _2100157b5d | Japanische Zierkirsche 'Kanzan' | SRID=4326;POINT(13.37779 52.55842) | 50     | panketaucher |

**Comment by vogelino** [comment]
Danke @panketaucher für der Bugreport! Tatsächlich ist diesen Bug aufgetaucht, jedesmal dass ein adoptierten bzw. zuletzt bewässerten Baum kein Alter in unser Datenbank hatte. Irgendeine logischer Check hat dafür gesorgt, dass der Bäume ohne alter nicht in der Altersspanne gefallen sind und deshalb versteck wurden. Dies wird ab jetzt erst dann gemacht, wenn der Alterfilter aktiv ist. Solche Bäume sollten also standardmässig korrekt angezeigt werden.

Danke und ich hoffe dass wir damit das Problem für dich gelöst haben! Grüße!
