### ISSUE TITLE
Adapt color scale of trees to also be influenced by user waterings 

### ISSUE THREAD

**Issue by vogelino** [technologiestiftung/giessdenkiez-de#383]
## Background: Why this issue? 

Currently, the color scale of trees in the default view is only based on the amount of rainwater but isn't influenced by how much water was added by the users. 

This doesn't help users to identify which trees are lacking water and which don't. Even if it is possible to know which trees were watered in the last 30 days, all trees are colored the same and each tree needs to be clicked individually in order to know their watering amount.

## Deliverables: How to fix the issue?

The API currently returns a list of trees and whether they were watered or adopted, but as a value of the watered property, the total amount of waterings is returned instead of the total liters of water. This could easily be fixed by changing the query [on this line](https://github.com/technologiestiftung/giessdenkiez-de-postgres-api/blob/956d8fa35c0641aee35aa4bac12dbb263a285315/api/_utils/db/db-manager.ts#L76) to sum the watering liters here.
This new value containing the total liters of water could then be added to the value passed to `interpolateColor` and thereby influence the final color of a tree.

## Output: Gain of fixing the issue?

Adding this would:
1. Better show how the community influences the watering of trees
2.Better identify which trees are lacking water

## Issue creation checklist

- [x] I have attached one of the priority labels `HIGH`, `MIDDLE`, `LOW`
- [x] I have attached other labels with regard to the issues purpose (i.e.`enhancement`, `bug`, `community feedback`)

**Comment by HenrietteN** [comment]
Closing this tickets as we have implemented this feature in the updated interface: https://www.giessdenkiez.de/map. Now the tree changes its colour for 30 days after a user entered a watering.
