### ISSUE TITLE
[Bug] Homepage is always loading twice: first loading, then login, then again loading; this takes a lot of time and wastes resources

### ISSUE THREAD

**Issue by Wikinaut** [technologiestiftung/giessdenkiez-de#471]
### How to reproduce

* goto https://giessdenkiez.de
* Page loads the Baumbestand 8xx.xxx trees - takes 10-30 seconds.
* Only now you can login.

### Bug

* Page loads the Baumbestand 8xx.xxx trees again - takes 10-30 seconds

### Proposed solution

* recode the login or save the credentials in cookies or local storage

Browser: Firefox 102.0.1

**Comment by ff6347** [comment]
Hi @Wikinaut Thanks for your suggestion. We currently don't have the resources to work actively on giessdenkiez. But we will add your suggestion to our backlog.

**Comment by julizet** [comment]
Hi @Wikinaut, 
our latest migration should have fixed this issue. We use another authentification flow now (Auth0 is deprecated) that uses Supabase as the backend. If the user logs in now, the only the user profile information such as watered and adopted trees are loaded which reduces the traffic and makes the website much faster.

Thanks for pointing out to this issue
