### ISSUE TITLE
[Verbesserungsvorschlag] Laufende Wässerungssumme über 7 und über 30 Tage anzeigen

### ISSUE THREAD

**Issue by Wikinaut** [technologiestiftung/giessdenkiez-de#475]
![grafik](https://user-images.githubusercontent.com/1151915/180214492-1d688889-5b50-47fc-bd85-21f4b221b42d.png)

Es gibt eine Summenfunktion, die macht irgendetwas, was sich mir nicht erschließt. Offenbar summiert die nur die Summe der Gießungen an einem Tag.

Ich schlage vor, eine laufende Summe der Wässerungen über 7 und über 30 Tage anzuzeigen.

**Comment by ff6347** [comment]
Hi @Wikinaut Thanks for your suggestion. Same comment as in #471
We currently don't have the resources to work actively on giessdenkiez. But we will add your suggestion to our backlog.

**Comment by julizet** [comment]
@Wikinaut we are currently working on that. Looking forward to a merge into main by the end of this week
See [this PR](https://github.com/technologiestiftung/giessdenkiez-de/pull/611)

**Comment by HenrietteN** [comment]
@Wikinaut we have updated the water need section, which now summarizes the received rain as well as watered amount per tree over the past 30 days. Therefore closing this tickets.
