### ISSUE TITLE
Test new DB with NextJs version of the App

### ISSUE THREAD

**Issue by vogelino** [technologiestiftung/giessdenkiez-de#518]

**Comment by ff6347** [comment]
I'm pretty confident that this works. I still would love to have an additional set of eyes to test this

**Comment by vogelino** [comment]
Great! What are the steps needed to test this? Adding other values in the .env file that's it? I couldn't find the in 1P.

**Comment by vogelino** [comment]
@ff6347 I've tested it on desktop and in the mobile emulation and it worked like a charm. I did test:
- All layers (trees, pumps, rain)
- Filters
- Login/Logout, delete account, create account
- Select tree, adopt/unadopt, water, remove watering
- Navigation (switch between tabs, check info, etc)
- Splash screen
- Zoom in, pan, etc on the map

It all looks good to me! :)
