### ISSUE TITLE
Test new DB on Vercel Preview

### ISSUE THREAD

**Issue by vogelino** [technologiestiftung/giessdenkiez-de#519]

**Comment by ff6347** [comment]
Same as #518 I think it work but would love a review from someone else

**Comment by vogelino** [comment]
@ff6347 I have tested the deployed version of this on the branch `test-new-db-on-vercel` using a custom domain [test-giessdenkiez-de.vercel.app](https://test-giessdenkiez-de.vercel.app) and everything also worked well there. I think we can close this!
