### ISSUE TITLE
function getWatered is not used?

### ISSUE THREAD

**Issue by ff6347** [technologiestiftung/giessdenkiez-de#552]
While reviewing API routes and functions and their counterpart on the API I noticed that the function below seems to be dead code. The function is not used on the code base. Which also means that the route is obsolete in the API.

Can you have a look @dnsos 

https://github.com/technologiestiftung/giessdenkiez-de/blob/e1e14cf2c1f0244414471704bebf003625044109/src/utils/requests/getWateredTrees.ts#L4

**Comment by ff6347** [comment]
I need a second pair of 👀

**Comment by dnsos** [comment]
@ff6347 confirmed. We can remove that request and the API route!

**Comment by ff6347** [comment]
Cool
