### ISSUE TITLE
Ordering of list of last waterings should be fixed

### ISSUE THREAD

**Issue by ghburdie** [technologiestiftung/giessdenkiez-de#596]
Priority: `MIDDLE` Issue Type: `bug`

### Background: Why this issue? 
When showing information about a single tree in section "_Last Waterings (Letzte Bewässerungen)_", the list of watering events is ordered from **oldest first to newest last** (the opposite of how it is indicated in the subtitle!). [This](https://www.giessdenkiez.de/tree/_21002208e0) is an example tree with a list of watering events.

### Deliverables: How to fix the issue?
The list should be ordered from **newest first to oldest last**, like indicated in the subtitle "_Newest first (Neueste zuerst)_".

### Output: Gain of fixing the issue?
The user can see *without* further clicking, when the tree was watered the last time. It is more interesting/important for the user than the first watering X years ago.

**Comment by ghburdie** [comment]
_Problem of false ordering of list of last waterings seems to be fixed._
# Thank You!

**Comment by julizet** [comment]
Hi @ghburdie, 

Indeed the ordering of the waterings was fixed mid of June this year. You can find the code changes here https://github.com/technologiestiftung/giessdenkiez-de/commit/f57c1f43aa596f83db396e8aa4fcec4328df4fc3

thank you for taking care of reporting and closing this issue.
