### ISSUE TITLE
DWD Harvester action is failing

### ISSUE THREAD

**Issue by JensWinter** [technologiestiftung/giessdenkiez-de#687]
Hi GDK-Team! Hi @Jaszkowic!

today the magdeburg-giesst DWD Harvester failed. And I've noticed that the GDK DWD harvester failed too. Establishing the database connection doesn't work anymore. And you seemed to have fixed the issue. Could you tell me what you did to fix that?

Jens

**Comment by Jaszkowic** [comment]
Hi @JensWinter, indeed, we also had troubles with connecting to the databases. The reason for this is that Supabase has changed how we can directly connect to the database:

> We’re deprecating PgBouncer and migrating all projects to our Supavisor connection pooler. Go grab the pooler connection string in your project’s [Database Settings](https://supabase.com/dashboard/project/_/settings/database).

Changing the environment variables for the DWD Harvester to point to the new database endpoint worked for us.

**Comment by JensWinter** [comment]
Hey thanks for your hint.

Oh, and I thought I did that and it didn't work.
Well, obviously it's not enough to just change the server name. I forgot to set up the correct user name as well. Now it's working. Thanks again. 😃
