### ISSUE TITLE
Cannot toggle filter button back to non active

### ISSUE THREAD

**Issue by ff6347** [technologiestiftung/giessdenkiez-de#80]

**Comment by julizet** [comment]
What is the current status of this issue @ff6347 ?

**Comment by julizet** [comment]
What is the current status of this issue @ff6347 ?

**Comment by ff6347** [comment]
I actually don't remember what that was…

**Comment by julizet** [comment]
me neither. I assume that this "non-active" status was dealing with the sidebar or the legend. However, both components are working fine so far. So let's close this issue
