### ISSUE TITLE
Reintroduce Link to OSM water well editor

### ISSUE THREAD

**Issue by tordans** [technologiestiftung/giessdenkiez-de#873]
We added a link to a MapComplete Water Well Editor in https://github.com/technologiestiftung/giessdenkiez-de/issues/460 and I am surprised to see that it was removed. 
> <img width="503" alt="image" src="https://github.com/technologiestiftung/giessdenkiez-de/assets/111561/6b51611d-0b9f-4420-8e84-98ea15e3ab7d">
[Source](https://www.giessdenkiez.de/map?lat=52.472420675160805&lng=13.446626085788125&zoom=20&treeAge=young&treeAge=medium&treeAge=old&isPumpsVisible=true)

To be honest, I am even more surprised that it was removed without any ping to me / the Berlin OSM Community about it. We have been promoting the app as a great example of collaborative data editing with OSM… which apparently it not true anymore.

With the start of the new season of public water well checking I updated the MapComplete theme this week to get it working with the latest MapComplete version. It is now hosted on MapComplete infrastructure at https://mapcomplete.org/theme.html?lat=52.47271334046087&lon=13.445970188175806&userlayout=https%3A%2F%2Fstudio.mapcomplete.org%2F11881%2Fthemes%2Fberlin_emergency_water_pumps%2Fberlin_emergency_water_pumps.json

Are you open to adding the link back to the dialogue?
Is that something you can add or would you prefer a PR from us?

**Comment by tordans** [comment]
@ff6347 that is wonderful to hear. Feel free to ping me any time those things break!

The new theme works and can be updated more easily should it break. The URL template string should be something like
`https://mapcomplete.org/theme.html?userlayout=https%3A%2F%2Fstudio.mapcomplete.org%2F11881%2Fthemes%2Fberlin_emergency_water_pumps%2Fberlin_emergency_water_pumps.json#node/760002892` where `760002892` needs to updated with the given OSM id.

**Comment by Jaszkowic** [comment]
Hi @tordans I'm currently working on bringing the pump link back. I tried out the link for a specific pump:

https://mapcomplete.org/theme.html?userlayout=https%3A%2F%2Fstudio.mapcomplete.org%2F11881%2Fthemes%2Fberlin_emergency_water_pumps%2Fberlin_emergency_water_pumps.json#node/7386146825

which removed the node id while redirecting to 

https://mapcomplete.org/theme.html?z=15.1&lat=52.47271334046306&lon=13.445970188177284&userlayout=https%3A%2F%2Fstudio.mapcomplete.org%2F11881%2Fthemes%2Fberlin_emergency_water_pumps%2Fberlin_emergency_water_pumps.json 

(Tried out in incognito mode)

Can you provide a working link which leads directly to a pump? e.g. pump id = `7386146825`

Thanks!

**Comment by tordans** [comment]
> Can you provide a working link which leads directly to a pump? e.g. pump id = `7386146825`

Sorry, I thought I did. We had this issue in the last code as well which is why the lat/lng/zoom was added in the last code. But I hope there is a cleaner solution and I asked in the MapComplete Matrix channel about it. 

The Link that would work right away is `https://mapcomplete.org/theme.html?lat=52.472533988064754&lon=13.447968997300677&userlayout=https%3A%2F%2Fstudio.mapcomplete.org%2F11881%2Fthemes%2Fberlin_emergency_water_pumps%2Fberlin_emergency_water_pumps.json#node/760002892` where the lat/lon need to be that (or nearby) the given node id.

**Comment by raphael-arce** [comment]
@tordans is this issue resolved or is there still something to be done?
