### ISSUE TITLE
Please remove ff6347 as a CODEOWNER

### ISSUE THREAD

**Issue by ff6347** [technologiestiftung/giessdenkiez-de#945]
The user @ff6347 is listed in the CODEOWNERS file but should be removed.

**Comment by raphael-arce** [comment]
@ff6347 Done 👍  will close this issue

**Comment by ff6347** [comment]
![scared-homer-simpson-gif-by-reactionseditor](https://github.com/user-attachments/assets/f20b9588-f813-4c20-aca7-d667256ee7ff)
